if ( GetLocale() == "frFR" ) then
	--ZG & AQ Items
	Raids_Items = {"Idole d'albâtre",
		"Idole en ambre",
		"Idole azur",
		"Idole de la mort",
		"Idole de la vie",
		"Idole de la nuit",
		"Idole de la renaissance",
		"Idole de la lutte",
		"Idole de la guerre",
		"Idole du sage",
		"Idole du soleil",
		"Idole de jaspe",
		"Idole diaprée",
		"Idole en obsidienne",
		"Idole en onyx",
		"Idole vermillon",
		"Scarabée d'os",
		"Scarabée en bronze",
		"Scarabée d'argile",
		"Scarabée de cristal",
		"Scarabée d'or",
		"Scarabée d'ivoire",
		"Scarabée d'argent",
		"Scarabée de pierre",
		"Clé de coffre de scarabées",
		"Clé de coffre de scarabées supérieur",
		"Bijou Hakkari rouge",
		"Bijou Hakkari bleu",
		"Bijou Hakkari jaune",
		"Bijou Hakkari orange",
		"Bijou Hakkari vert",
		"Bijou Hakkari violet",
		"Bijou Hakkari bronze",
		"Bijou Hakkari argenté",
		"Bijou Hakkari doré",
		"Pièce zulienne",
		"Pièce Razzashi",
		"Pièce hakkari",
		"Pièce Gurubashi",
		"Pièce Vilebranche",
		"Pièce Fânécorce",
		"Pièce Furie-des-sables",
		"Pièce Casse-crâne",
		"Pièce Scalp-rouge",
		"Noyau de feu",
		"Noyau de lave",
	"Minerai d'élémentium"}
	
	else
	--ZG & AQ Items
	Raids_Items = {"Alabaster Idol",
		"Amber Idol",
		"Azure Idol",
		"Idol of Death",
		"Idole of Life",
		"Idole of Night",
		"Idole of Rebirth",
		"Idole of Strife",
		"Idole of War",
		"Idole of the Sage",
		"Idole of the Sun",
		"Jasper Idol",
		"Lambent Idol",
		"Obsidian Idol",
		"Onyx Idol",
		"Vermillon Idol",
		"Bone Scarab",
		"Bronze Scarab",
		"Clay Scarab",
		"Crystal Scarab",
		"Gold Scarab",
		"Ivory Scarab",
		"Silver Scarab",
		"Stone Scarab",
		"Scarab Coffer Key",
		"Greater Scarab Coffer Key",
		"Red Hakkari Bijou",
		"Blue Hakkari Bijou",
		"Yellow Hakkari Bijou",
		"Orange Hakkari Bijou",
		"Green Hakkari Bijou",
		"Purple Hakkari Bijou",
		"Bronze Hakkari Bijou",
		"Silver Hakkari Bijou",
		"Gold Hakkari Bijou",
		"Bloodscalp Coin",
		"Skullsplitter Coin",
		"Vilebranch Coin",
		"Witherbark Coin",
		"Sandfury Coin",
		"Hakkari Coin",
		"Razzashi Coin",
		"Gurubashi Coin",
		"Zulian Coin",
		"Lava Core",
		"Fiery Core",
	"Elementium Ore"}
end		